Adds slurm tests, updates test runner to exit 1 if any tests fail

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,11 +1,27 @@
 #!/bin/bash
-COVERAGE_FILE=.coverage_setup coverage run --source=.,lib,jobs --omit="lib/test*","*__init__.py" lib/test_setup.py
-COVERAGE_FILE=.coverage_yearset coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py" lib/test_yearset.py
-COVERAGE_FILE=.coverage_filemanager coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py" lib/test_filemanager.py
-COVERAGE_FILE=.coverage_util coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py" lib/test_util.py
+FAILED=0
+COVERAGE_FILE=.coverage_setup coverage run --source=.,lib,jobs --omit="lib/test*","*__init__.py","setup.py" lib/test_setup.py
+if [ ! $? ]; then
+    $FAILED=1
+fi
+COVERAGE_FILE=.coverage_yearset coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_yearset.py
+if [ ! $? ]; then
+    $FAILED=1
+fi
+COVERAGE_FILE=.coverage_filemanager coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_filemanager.py
+if [ ! $? ]; then
+    $FAILED=1
+fi
+COVERAGE_FILE=.coverage_util coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_util.py
+if [ ! $? ]; then
+    $FAILED=1
+fi
+COVERAGE_FILE=.coverage_slurm coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_slurm.py
+if [ ! $? ]; then
+    $FAILED=1
+fi
 
-coverage combine .coverage_setup .coverage_util .coverage_yearset .coverage_filemanager
-rm .coverage_setup .coverage_util .coverage_yearset .coverage_filemanager
+coverage combine .coverage_setup .coverage_util .coverage_yearset .coverage_filemanager .coverage_slurm
 coverage report
 coverage html
 coverage xml
@@ -14,6 +30,12 @@ if [ -d /var/www/acme/acme-diags/baldwin32/htmlcov ]; then
     rm -rf /var/www/acme/acme-diags/baldwin32/htmlcov
 fi
 mv htmlcov /var/www/acme/acme-diags/baldwin32
+rm slurm-*
 
-echo "tests done"
-echo "report available at http://acme1.llnl.gov/baldwin32/htmlcov/index.html"
+if [ $FAILED == 1]; then
+    echo "One or more tests failed"
+    exit 1
+else
+    echo "tests done"
+    echo "report available at https://acme-viewer.llnl.gov/baldwin32/htmlcov/"
+fi
